server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantmanager
    username: root
    password: Mangesh@09
    driver-class-name: com.mysql.cj.jdbc.Driver
  r2dbc:
    properties:
      useSSL: false
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: configserver:http://localhost:8088
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/restaurantMapping/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotelservice/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratingsmanager/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka







